// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqjfYDAxXaqlxmVcPNrYdCMgLcHRXoSfg',
    appId: '1:611414949138:web:fc42da9e75e3dc4a0f07cb',
    messagingSenderId: '611414949138',
    projectId: 'ella-ffd84',
    authDomain: 'ella-ffd84.firebaseapp.com',
    storageBucket: 'ella-ffd84.firebasestorage.app',
    measurementId: 'G-QWH92CZ0CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ahvP031JTV6zouWCT4YdP724FMW2xBc',
    appId: '1:611414949138:android:2d78a4562989fdd00f07cb',
    messagingSenderId: '611414949138',
    projectId: 'ella-ffd84',
    storageBucket: 'ella-ffd84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI712gWqlFZXftiLlpbKcIVp2yvgSQ-BM',
    appId: '1:611414949138:ios:a05cffca01ced52c0f07cb',
    messagingSenderId: '611414949138',
    projectId: 'ella-ffd84',
    storageBucket: 'ella-ffd84.firebasestorage.app',
    iosBundleId: 'com.example.geminiChatAppTutorial',
  );
}
