// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNM6KWWvov1SRpKoNEOYZvjs7aaiBfwxw',
    appId: '1:683567834719:web:e3f197bffe11b243251dea',
    messagingSenderId: '683567834719',
    projectId: 'ellaai-7c108',
    authDomain: 'ellaai-7c108.firebaseapp.com',
    storageBucket: 'ellaai-7c108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNM6KWWvov1SRpKoNEOYZvjs7aaiBfwxw',
    appId: '1:683567834719:android:e3f197bffe11b243251dea',
    messagingSenderId: '683567834719',
    projectId: 'ellaai-7c108',
    storageBucket: 'ellaai-7c108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCw67vFGmNk_sNt-giurY2KXBwrH9qzhs',
    appId: '1:683567834719:ios:a8f0ff6e6c102775251dea',
    messagingSenderId: '683567834719',
    projectId: 'ellaai-7c108',
    storageBucket: 'ellaai-7c108.firebasestorage.app',
    iosBundleId: 'com.Hoocup.hoocup',
  );
}


